refactor(*): dev env setup, code cleanup
DiscordDevelopmentDiscord/ddd-join pull request #1
Opened 2021-06-28 00:33 UTC by zaida04

> ### ⚠️ Don't merge yet! This PR is awaiting testing and review from @vladfrangu

## What does this PR accomplish?
- [x] ESLint & Prettier (and config)
- [x] Husky Pre-commit hooks (in connection with lint-staged and commitlint)
- [x] General "makeRequest" function that all fetch requests are abstracted to.
- [x] Fully type all outgoing requests made so that the code is type-safe.
- [x] Cleanup of the code (condensing variables, renaming, etc.)

## That's cool, why?
![image](https://media1.tenor.com/images/c2fcc3b1b638dfae552d8ac8c330b1fa/tenor.gif?itemid=15489594)

2021-06-28 16:17 UTC, jb3 commented
API ratelimits are likely not necessary to handle. We won't hit them.

2021-06-28 16:27 UTC, vladfrangu requested changes

2021-06-28 16:27 UTC, vladfrangu commented on src/bindings.d.ts
> +import { Snowflake } from 'discord-api-types'
Please import from a version or from /globals

2021-06-28 16:27 UTC, vladfrangu commented on src/index.ts
>  import { getErrorPageHTML, Router } from '8track'
It seems like eslint isn't linting these files, no semis?

2021-06-28 16:27 UTC, vladfrangu commented on src/index.ts
> +		if (!userGuilds.some((x) => WHITELISTED_GUILDS.includes(x)))
Faster to reverse this some check (check if either allowed guild is in the users guild

2021-06-28 16:27 UTC, vladfrangu commented on src/oauth2.ts
> +// eslint-disable-next-line no-duplicate-imports
Don't duplicate imports

2021-06-28 16:27 UTC, vladfrangu commented on src/util.ts
> +	return [req.json() as Promise<T>, req]
```suggestion
	return [await req.clone().json() as Promise<T>, req]
```

2021-06-30 09:21 UTC, vladfrangu requested changes

2021-06-30 09:21 UTC, vladfrangu commented on .lintstagedrc.json
> +    "*.ts": "eslint --fix"
Can you do this like we do in, say, discord-api-types? (the whole --ext and all

2021-06-30 09:21 UTC, vladfrangu commented on src/index.ts
> +		const accessToken = accessTokenBody['access_token'];
Use dot notation

2021-06-30 09:21 UTC, vladfrangu commented on src/index.ts
> +				`An unexpected error occurred while joining you to the guild. Your authorization token could not be revoked, you can do so in your Discord client under User Settings > Authorized Apps`,
Inaccurate per say, this error is if we couldn't revoke the token, not if we couldn't add you to a guild. Should handle that case too

2021-07-02 21:45 UTC, vladfrangu approved these changes

2021-07-03 01:08 UTC, jb3 approved these changes

2021-07-03 01:08 UTC, merged